<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KU75J3L" ignored="0" name="MultipleRetryLogicTest" tests="8" failures="2" timestamp="17 May 2020 14:03:54 GMT" time="0.117" errors="0">
  <testcase name="method1" time="0.012" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.003" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.005" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.003" classname="testseleniumpromain.RetryLogictest">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testseleniumpromain.RetryLogictest.method1(RetryLogictest.java:14)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method2" time="0.004" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.001" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.003" classname="testseleniumpromain.RetryLogictest">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.002" classname="testseleniumpromain.RetryLogictest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testseleniumpromain.RetryLogictest.method2(RetryLogictest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
</testsuite> <!-- MultipleRetryLogicTest -->
